### ISSUE TITLE
Support recursive variables

### ISSUE THREAD

**Issue by Swatinem** [polyfills/variables#1]
The following code:

``` css
:root {
    --color-border: black;
    --border: 1px solid var(--color-border);
}
div {
    border: var(--border);
}
```

is translated to:

``` css
:root {
    --color-border: black;
    --border: 1px solid black;
}
div {
    border: 1px solid color-border;
}
```

The first substitution inside `:root` is correct, but the second is just wrong.
(Just filing this since nlz includes this. But maybe the better solution is just to switch to a more robust css postprocessor)
